Repository Crew-Wiki/crew-wiki-next, pull requests merged in 2025-07, with the labels that each got.

#96 문서 편집로그 페이지네이션으로 불러오는 기능 구현
  client/src/apis/client/document.ts
  client/src/apis/server/document.ts
  client/src/app/wiki/[uuid]/logs/LogContent.tsx
  client/src/app/wiki/[uuid]/logs/LogList.tsx
  client/src/app/wiki/[uuid]/logs/page.tsx
  client/src/components/common/InfinityScrollObserver/index.tsx
  client/src/constants/params.ts
  client/src/hooks/fetch/useGetDocumentLogs.ts
  client/src/type/Document.type.ts
Labels: 🖥️ FE, ⚙️ feat

#103 tailwind prettier style 적용
  client/package.json
  client/src/app/wiki/statistics/page.tsx
  client/src/components/common/FloatingButton/index.tsx
  client/src/components/common/Input/index.tsx
  client/src/components/common/SearchTerms/RelativeSearchTerms.tsx
  client/src/components/document/layout/DocumentFooter.tsx
  client/src/components/layout/Header/RightHeader.tsx
  client/src/components/layout/Header/WikiHeader.tsx
Labels: ⚙️ feat, 🚧 refactor

#106 존재하지 않는 문서 url에서 500 에러 발생하는 문제 해결
  client/src/app/wiki/[uuid]/page.tsx
  client/src/utils/getDocumentUsingUUIDInCache.ts
Labels: 🚨 bug, 🖥️ FE, Medium

#107 대문 리다이렉션 처리
  client/next.config.ts
Labels: 🖥️ FE, ⚙️ feat

#110 이미지 한번에 하나씩 올리는 기능으로 변경
  client/src/apis/client/images.ts
  client/src/app/wiki/[uuid]/edit/page.tsx
  client/src/app/wiki/[uuid]/log/[logId]/page.tsx
  client/src/app/wiki/[uuid]/page.tsx
  client/src/app/wiki/post/page.tsx
  client/src/components/document/TuiEditor/index.tsx
  client/src/components/document/Write/PostHeader.tsx
  client/src/components/document/layout/MobileDocumentHeader.tsx
  client/src/hooks/mutation/useUploadImage.ts
  client/src/hooks/useMutation.ts
  client/src/store/document.ts
  client/src/type/Document.type.ts
  client/src/type/Editor.type.ts
  client/src/utils/replaceLocalUrlToS3Url.ts
Labels: 🖥️ FE, ⚙️ feat
