Repository Crew-Wiki/crew-wiki-next, pull requests merged in 2025-05, with the labels that each got.

#62 프로젝트 상태 관리 액션 연결
  .github/auto_assign.yml
  .github/workflows/close-issue-on-pr-merge.yml
  .github/workflows/create-issue.yml
  .github/workflows/pr-issue-close.yml
  .github/workflows/start-issue.yml
  .github/workflows/sync-issue-to-pr.yml
Labels: 🖥️ FE, 🛠️ Setting

#66 DocumentTitle 컴포넌트 className 오타 수정
  client/src/components/document/layout/DocumentTitle.tsx
Labels: 🚨 bug, 🖥️ FE

#68 Prettier 설정 및 Tailwind 클래스 정렬 Plugin 추가
  .vscode/settings.json
  client/.prettierignore
  client/.prettierrc
  client/package.json
  client/yarn.lock
Labels: 🖥️ FE, 🛠️ Setting

#69 디렉터리 내 이미지 CDN으로 이동
  client/next.config.ts
  client/src/app/image/hangseong-white.png
  client/src/app/image/icon.svg
  client/src/app/image/search-circle-secondary.svg
  client/src/app/image/search-circle.svg
  client/src/app/layout.tsx
  client/src/app/wiki/[title]/page.tsx
  client/src/components/layout/Header/RightHeader.tsx
  client/src/components/layout/Header/WikiHeader.tsx
  client/src/components/layout/Header/WikiInputField.tsx
  client/src/import-env.d.ts
Labels: 🖥️ FE, ⚙️ feat
